import { SimpleGrid } from '@chakra-ui/react';
import type { NextPage } from 'next'
import Head from 'next/head'
import UserCard from '@/components/UserCard';
import { realPenguin } from '@/data/users'
import IUser from '@/types/user';

const About: NextPage = () => {
  return (
    <div>
      <Head>
        <title>{`About - RealPenguin Blog`}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <SimpleGrid columns={[1, 3, 1, 3]}>
          <UserCard user={realPenguin} />
      </SimpleGrid>
    </div>
  )
}

export default About
