import { SimpleGrid } from '@chakra-ui/react';
import type { NextPage } from 'next'
import Head from 'next/head'
import UserCard from '../components/UserCard';
import { realPenguin } from '../data/users'
import IUser from '../types/user';

const users = [realPenguin];

type Props = {
    users?: [IUser]
}

const About: NextPage<Props> = ({ users }) => {
  return (
    <div>
      <Head>
        <title>{`About - RealPenguin Blog`}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <SimpleGrid columns={[1, 3, 1, 3]}>
        {users?.map((user) => (
            <UserCard key={user.name} user={user} />
        ))}
      </SimpleGrid>
    </div>
  )
}

export default About
