import { Container as ChakraContainer, SimpleGrid } from '@chakra-ui/react';
import type { NextPage } from 'next'
import Container from '@/components/Container';
import Head from 'next/head'
import UserCard from '@/components/UserCard';
import { realPenguin } from '@/data/users'

const About: NextPage = () => {
  return (
    <Container title='About - RealPenguin Blog' description='Generated by create next app'>
      <ChakraContainer>
        <SimpleGrid columns={[1, 3, 1, 3]}>
            <UserCard user={realPenguin} />
        </SimpleGrid>
      </ChakraContainer>
    </Container>
  )
}

export default About
