import type { NextPage } from 'next'
import Head from 'next/head'

const Discord: NextPage = () => {
  return (
    <div>
      <Head>
        <title>{`Discord Member - RealPenguin Blog`}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
    </div>
  )
}

export default Discord
