import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'

type Data = {
    fallbackData?: any;
}

const GuestbookPage: NextPage<Data> = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  )
}

export const getStaticProps: GetStaticProps = async (context) => {
  return {
      props: {
      }
  }
}

export default GuestbookPage
